
USE EMPLOYEE_DB


CREATE TABLE USERS
(
  ID  INT PRIMARY KEY IDENTITY (1, 1) NOT NULL,
  USERNAME    VARCHAR (MAX) NULL,
  PASSWORDS  VARCHAR (MAX) NULL,
  DATE_REGISTER DATE NULL
);


SELECT * FROM USERS

CREATE TABLE EMPLOYEES
(
ID INT PRIMARY KEY IDENTITY(1,1),
EMPLOYEE_ID VARCHAR(MAX),
FULL_NAME VARCHAR(MAX),
GENDER VARCHAR(MAX),
CONTACT_NUMBER VARCHAR(MAX),
POSITION VARCHAR(MAX),
IMAGES VARCHAR(MAX),
SALARY INT,
INSERT_DATE DATE,
UPDATE_DATE DATE,
DELETE_DATE DATE
);

ALTER TABLE EMPLOYEES
ADD STATUS VARCHAR(MAX);

SELECT * FROM EMPLOYEES